import { Button } from './Button.js';
import { Datalist } from './Datalist.js';
import { Fieldset } from './Fieldset.js';
import { FileInput } from './FileInput.js';
import { Form } from './Form.js';
import { Label } from './Label.js';
import { Legend } from './Legend.js';
import { Option } from './Option.js';
import { Select } from './Select.js';
import { TextArea } from './TextArea.js';
import { TextInput } from './TextInput.js';
export { Button, Datalist, Fieldset, FileInput, Form, Label, Legend, Option, Select, TextArea, TextInput };
